plugins:
  - '@dotcom-tool-kit/component'
  - '@dotcom-tool-kit/mocha'
  - '@dotcom-tool-kit/eslint'
hooks:
  test:local:
    - Eslint
    - Mocha
  test:ci:
    - Eslint
    - Mocha
options:
  '@dotcom-tool-kit/circleci':
    nodeVersion:
      - '20.15'
      - '18.20'
